scipy/scipy.org

www/.htaccess
www/_templates/sitenav.html
www/bug-report.rst
www/getting-started.rst
www/scipylib/building/linux.rst
www/topical-software.rst

Let's pronounce wiki.scipy.org dead.
It's not been a wiki for many years (read-only), and it's been offline for the past month anyway. [There's also not very much material that's still useful in there](http://pav.iki.fi/tmp/to-be-removed/localhost_8080/AllPages.html). So best to not direct users there.
The Scipy-Cookbook perhaps could have a new life in a different form (cf https://github.com/pv/SciPy-CookBook/tree/master/ipython), but as it is now, much of the material is outdated and does things in an unnecessarily clumsy way. I removed links to it --- it may be more confusing than useful --- it's probably better to redirect people to read tutorials instead.

Remove links to wiki.scipy.org

---

www/citing.rst

The javascript on the "citing" page contains an infinite loop.
Fix it.

Fix infinite loop in added javascript

---

www/scipylib/download.rst

Orion Poplawski on ML, https://mail.scipy.org/pipermail/scipy-dev/2016-February/021233.html
> I'll note that 
> http://www.scipy.org/scipylib/download.html#official-source-and-binary-releases 
> still points to the sourceforge site which does not appear to be updated.

MAINT: clarify the status of the scipy sourceforge page

---

www/scipylib/building/windows.rst

Addresses issue #145 by revamping / updating the documentation on building source from Windows to provide a more organized format as well as to reflect ongoing projects like <a href="http://mingwpy.github.io/">Mingwpy</a> that users should be aware of.  Related to `numpy` issue <a href="https://github.com/numpy/numpy/issues/5479">#5479</a>
@matthew-brett, @carlkl, @njsmith, @rgommers, @juliantaylor, @tkelman

DOC: Revamp Building from Source on Windows

---

www/topical-software.rst

Just a minor change to include a link to my paramnormal package as suggested by @ev-br:
https://github.com/phobson/paramnormal/issues/32#issuecomment-193934691

DOC: added link to paramnormal in topical software

---

www/topical-software.rst

Hi,
I would like to add two optimization packages to the topical software list.
The first, noisyopt https://github.com/andim/noisyopt, is a library for the optimization of noisy functions. It currently includes a stochastic perturbation stochastic approximation algorithm and a pattern search algorithm with adaptive sampling.
The second, scipydirect https://github.com/andim/scipydirect, is a wrapper around the DIRECT global optimization algorithm.
Both packages are lightweight and provide a scipy.optimize compatible call syntax to allow easy interchangeability with the optimization algorithms from scipy, which is crucial to allow fast testing of different algorithms on a given optimization problem.
Cheers
Andreas

added noisyopt and scipydirect to python optimization topical software

---

www/bug-report.rst

It seems that the wording on the bug tracker page may be confusing.
Try to word it more clearly to indicate that the website bug tracker is not scipy bugtracker.

Try to be clearer that scipy.org bug tracker is not scipy bug tracker

---

www/install.rst

- Use Python 3.5 by default.
- Remove Gentoo, outdated and not big enough to maintain.
- Explain that for pip instructions to work, Python and pip need to already be installed.
- some minor cleanups

DOC: update and clean up install instructions

---

www/scipylib/download.rst

Most importantly, link to PyPI instead of SourceForge.

DOC: fix up scipylib download page

---

www/topical-software.rst

The link to the resource "learn python" was no longer working so I updated it. I added a new educational link to DataCamp's free interactive coding tutorial for python.

Updated broken link + added new data science resource

---

www/bug-report.rst

Try to make it clearer that docs issues should go to the relevant project

---

www/citing.rst

We recently published and the paper can be found here https://peerj.com/articles/cs-103/
We would love it to be included here.

Add SymPy paper to citing.rst

---

www/scipylib/mailing-lists.rst

Note that there is no scipy-dev Nabble forum, so we lost easy
searchability for scipy-dev.  We may look into creating such a forum
soon.

Update mailing lists page.  Remove links to Gmane, add Stackoverflow.

---

www/topical-software.rst

I've added the [Yellowbrick library](https://github.com/DistrictDataLabs/yellowbrick) to the list of topical software for the SciPy documentation. Yellowbrick ([http://www.scikit-yb.org/](http://www.scikit-yb.org/)) is a suite of visual analysis and diagnostic tools to facilitate feature selection, model selection, and parameter tuning for machine learning with Scikit-Learn. All visualizations are generated in Matplotlib, and the library features a consistent sklearn-like API.

adds Yellowbrick to topical software

---

www/topical-software.rst

Point pypi search links to https://pypi.org instead of
https://pypi.python.org/pypi -- the latter page nowadays says it's
deprecated interface, and it doesn't seem any longer possible to search
inside a specific category.
Drop links to scipy central.

topical-software: update links to PyPi, drop central

---

www/about.rst
www/stackspec.rst

* IPython Notebooks have been renamed
* Chaco and Mayavi seem to have lacked in traction and continued development
* Nose is unmaintained and not recommended
* scikit-{learn,image} deserve separate descriptions.

Update content on constituent packages

---

www/install.rst

Update the installation instructions:
- Remove references to the "scipy stack" (following #218)
- Promote using pip also on Windows
We may want to wait until scipy 1.0 is out in order to have the windows wheels...

Change installation instructions to promote pip + remove references to "scipy stack"

---

www/scipylib/mailing-lists.rst

Triggered by mailing list discussion starting on 22 Feb 2018.

DOC: add description of what the `scipy` IRC channel is for.

---

www/index.rst

Note: I also would like write permission to `docs.scipy.org` so I can upload the rebuilt docs with `make upload USERNAME=ahaldane RELEASE=v1.14.3`.

Announce NumPy 1.14.3 release

---

www/index.rst
www/past-news.rst

Also move old news to `past-news.rst`.

Announce NumPy 1.15.0

---

www/install.rst

As noted in numpy/numpy#11454 we should not recommend using homebrew to build scientific python packages.

deprecate using homebrew to build numpy, scipy

---

www/install.rst

The section [Scientific Python distributions](https://scipy.org/install.html#scientific-python-distributions) lista Anaconda. However, the link is at the moment pointing to
> https://www.continuum.io/downloads (<-- dead)
whereas it should in my opinion point to
> https://www.anaconda.com/download/ (<-- new)
I replaced the link in this PR.

Fix broken Anaconda link

---

www/citing.rst

I discussed this change with @rgommers.  I asked at some point that we remove the citation to my and Gaël's paper in favor of Travis's book.  However, I've received feedback that a) the new source is not available openly online, b) is harder to cite (no DOI, URL, etc.), and c) sends academic credit to a place where it is not very useful.  So, this PR adds the paper back as a *secondary* reference.  I leave the decision of whether to incorporate this change fully up to the team.
I think the solution, in the longer term, is to write a new NumPy paper.  Perhaps to accompany the release of NumPy 2.0, which shouldn't be too far off.  It will document all the changes that happened over the past two years, which are numerous.  I know there is interest in writing such a paper, and it may be the …

Add back NumPy citation as secondary source

---

www/conf.py

This was remove in MPL 3.0, and we didn't seem to use it anyway.
Can now use builtin ``only:: html`` rather than ``htmlonly::``

BLD: remove matplotlib.sphinxext.only_directive

---

.github/ISSUE_TEMPLATE.md

Attempt to direct people to use project bug trackers instead of this
one for errors in documentation.

GH: add issue template

---

www/citing.rst

- ~still a draft, formatting probably isn't quite right yet~
- ~not sure if we want to remove the old/website citation~
- may want to simply link to the BibTeX copy/paste website instead of using
all that inline space for the example entry
- ~I need to add the title of the preprint--forgot that!~
The main motivation is that it looks like, informally, the SciPy 1.0 manuscript will likely get published around January 2020, so we may want to try to get some benefit/citations on the preprint until that time.

MAINT: add SciPy arXiv preprint

---

www/install.rst

Canopy and Python-xy are no longer developed. Not sure about NeuroDebian, but it's too specific to mention there.
Also be more accurate about Anaconda vs Miniconda - the latter is better for anyone beyond the beginner stage.

DOC: update info on scientific distributions

---

www/topical-software.rst

Reason: DataCamp proved again today they're a toxic company (see one of many messages on this topic at https://twitter.com/juliasilge/status/1278458785242116097), and we are under no obligation to link to their site.

Remove link to DataCamp tutorial

---

www/about.rst

Adds NetworkX to the "Data and computation" category of the about page which describes the scipy ecosystem.

DOC: Add NetworkX to ecosystem page.

---

www/citing.rst

This PR does a few things:
* Move visually appealing line wrapping
* Fix `Vand erPlas` -> `VanderPlas` and (I think?) `{Jarrod Millman}, K.` -> `Millman, K. Jarrod`
* More common BibTeX style (e.g. don't need `{`/`}` for each surname, don't need `~` between first name initials)
* Remove `https://doi.org/` from doi entry

Fix BibTeX items

---

www/citing.rst

Should this include the full author list? Or is "et. al" more likely to be cited?
> Charles R. Harris, K. Jarrod Millman, Stéfan J. van der Walt, Ralf Gommers, Pauli Virtanen, David Cournapeau, Eric Wieser, Julian Taylor, Sebastian Berg, Nathaniel J. Smith, Robert Kern, Matti Picus, Stephan Hoyer, Marten H. van Kerkwijk, Matthew Brett, Allan Haldane, Jaime Fernández del Río, Mark Wiebe, Pearu Peterson, Pierre Gérard-Marchant, Kevin Sheppard, Tyler Reddy, Warren Weckesser, Hameer Abbasi, Christoph Gohlke & Travis E. Oliphant 
https://www.nature.com/articles/s41586-020-2649-2
https://www.scipy.org/citing.html

DOC: citing.rst: "Array programming with NumPy" (2020)

---

www/codes-of-conduct.rst

The current link for the NumPy COC is not available anymore.

DOC fix link to the NumPy COC

---

config.yaml
content/en/news.md

News are now automatically generated from the `/news` folder. Each file is a news. The way it works is still being defined.
Right now it will create a single news which will be displayed on the front page. It will (after a theme update) link to the current news listing we already have.
- https://github.com/scientific-python/scientific-python-hugo-theme/pull/66
To be defined:
- Do we want to separate releases from news?
- Do we want to create a news per release? This is needed right now.
- Other requirements?
EDIT:
Upstream changes made it possible to stay with a single page and have the banner defined in the preamble. This PR update the theme and add the preamble keyword.
- https://github.com/scientific-python/scientific-python-hugo-theme/pull/71

Use the new structure for News

---

content/en/news.md

* Announce SciPy 1.7.3
* I think the `news` stuff has already been reorganized a bit since I last did this so let me know if there's a better way

Announce SciPy 1.7.3

---

content/en/download.md

Remove old things like Fink or MacPort were versions are not getting updated anymore. Also fix broken links.

DOC: update third party package links

---

netlify.toml

https://deploy-preview-441--scipy-org.netlify.app/reports/lighthouse.html
Here is the plugin we are using:
https://github.com/netlify-labs/netlify-plugin-lighthouse
I had to do two things:
1. Installed plugin in the Netlify UI from this [direct in-app installation link](https://app.netlify.com/plugins/@netlify/plugin-lighthouse/install).
2.  Add this
```
[[plugins]]
package = "@netlify/plugin-lighthouse"
[plugins.inputs.thresholds]
performance = 0.5
accessibility = 0.9
best-practices = 0.9
seo = 0.9
pwa = 0.2
[plugins.inputs]
output_path = "reports/lighthouse.html"
``` 
to `netlify.toml`.  I changed `performance = 0.9` and `pwa = 0.9` to  `performance = 0.5` and `pwa = 0.2` b/c otherwise the CI failed.
```
Plugin "@netlify/plugin-lighthouse" failed
Error: Failed with error:
Error for …
```

Add lighthouse to neflify

---

content/en/install.md

Following the installation guide to install scipy system wide on fedora:
`sudo dnf install numpy scipy python-matplotlib ipython python-pandas sympy python-nose atlas-devel`
Produces the error:
```
No match for argument: scipy
No match for argument: sympy
Error: Unable to find a match: scipy sympy
```
I've updated the guide to include the correct package names:
`sudo dnf install python-numpy python-scipy python-matplotlib ipython python-pandas python-sympy python-nose atlas-devel`

Update Package Names for Fedora

---

content/en/about.md

I fixed a dead link for contributors in the [about](https://scipy.org/about/) page.
The THANKS.txt file does not exist now.
I think GitHub’s [contributors](https://github.com/scipy/scipy/graphs/contributors) page is a good option.
Let me know if there is any other good option.

Fix a dead link for contributors in the about page.

---

config.yaml
content/en/community.md

The documentation url was set to develop due to broken links. Since this issue is resolved, we can use the proper released version url.
I took the (lazy) opportunity to add SciPy meeting.

Doc URL to released version and meetups

---

content/en/install.md

This is a quick cleanup in response to https://github.com/scipy/scipy/issues/16308#issuecomment-1221684861, which pointed out that details on building from source were missing on the install page.

Make install page specific to SciPy and link to build docs

---

content/en/about.md

* pleased to report I'm covered at 20 % time and effort by LANL for SciPy/NumPy work now; this is not the same pot of funding as NASA ROSES, though those grant meetings still make sense as a coordination point I think
* permission to use the LANL logo is tricky--I think this is good enough unless they tell me otherwise; I couldn't quite decide if we wanted the list of partners and then the subset of logos below, but since it is just Quansight logo for now I just went under that logo, feel free to adjust..

Add LANL institutional partner

---

content/en/community.md
content/en/contribute.md

Because the link to the calendar is in the text heading, folks might miss it. I've included additional mentions of the calendar link and also added a mention to the new contributor meetings, which were not yet listed on the page.

Add links to calendar and mention new contributors meeting

---

content/en/community.md

As discussed in today's community meeting.
A few other details we discussed are already present at the Get Help page (stack overflow, for example) so I didn't add them here.

DOC: Add link to slack space

---

content/en/news.md

0.19.x links were broken. Also placed in chronological order

fix broken links to release notes

---

content/en/news.md

Announce SciPy `1.11.1`, which was released rapidly to account for a licensing violation in `1.11.0`. The latter release was yanked from PyPI just now.
I did not add any information about the yanking here, but at least it should be clear enough on PyPI.

Announce SciPy 1.11.1

---

content/en/install.md

Addresses part 2/2 in https://github.com/scipy/scipy/issues/18788
Fix the broken (outdated) link to the dev-build guide in install.md.

DOC: Fix broken link to dev-build in install.md

---

netlify.toml

We need this for recent versions of the theme.
See https://sass-lang.com/blog/libsass-is-deprecated/ and https://gohugo.io/hugo-pipes/transpile-sass-to-css/#dart-sass.

Use dart sass

---

config.yaml

Close #540. See https://github.com/scientific-python/scientific-python-hugo-theme/issues/398.

Add navbar logo text

---

config.yaml
content/en/_index.md

Building on functionality from the v0.11 release. The keyfeature panel for the homepage will be removed in a future theme release. This is part of our large effort to adopt styling from pydata-sphinx-theme where possible. It also makes the frontpage behave more like the other pages.
You can see more examples of cards (in a grid) here: 
- https://theme.scientific-python.org/shortcodes/#grid
This will also make it easier to modify your project homepage without having to override `layouts/index.html`.
The styling is a little different than before due to adopting pydata-sphinx-theme styling. But that styling is being used on many community sites and is being reviewed for accessibility.

Move keyfeatures to a grid of cards

---

content/en/_index.md

Switching to the new grid syntax.
v0.13
- add new syntax via grid1 to theme
- port website to grid1
v0.14
- cp grid1 to grid in theme
- replace grid1 with grid in websites
v0.15
- rm grid1 from theme
- nothing to do for websites

Use new grid syntax

---

requirements.txt

Close #563. Need a version that supports Python 3.9 (version on netlify). Specifying `pre-commit>=3.5.0` will prevent dependabot from trying to update it.

Loosen pre-commit pin

---

content/en/teams/maintainers.toml
content/en/teams/triage-team.toml

This is the output of `make teams`:
- adds Sean Cheah to the Maintainers team (Cc @thalassemia for visibility)
- updates an avatar that changed since the last run

Update Teams page

---

content/en/news.md

* Announce SciPy `1.13.0`, including a slightly longer blurb given the NumPy version support update.
(and fingers crossed...)

Announce SciPy 1.13.0

---

content/en/news.md

Announce SciPy `1.13.1`.
The final few steps of the release process, like docs upload and so on, will have to wait until tomorrow, it is late.

Announce SciPy 1.13.1

---

content/en/news.md

Announce SciPy 1.14.1

---

content/en/citing-scipy.md

There is no DOI link in the default citation, although there is one in the Bibtex. Adding it here makes it more likely for people to use it. 
This follows the format that Numpy uses, [here](https://numpy.org/citing-numpy/).

Add a DOI to the default citation

---

content/en/beginner-install.md
content/en/install.md

- Modernise discussion around installing from PyPI or conda-forge
- Include `uv` and `pixi` as options
- Add explanation of how to install with static type stubs
- remove mention of Python distributions and Anaconda `defaults` (https://github.com/scipy/scipy.org/pull/595#discussion_r1887539401)
cc @rgommers @stefanv @jarrodmillman @tupui @jorenham

Update installation page

---

content/en/faq.md

Update link to Pyjion in faq.md
New link: https://pythran.readthedocs.io/
Old link does not work.
https://www.trypyjion.com/

Update link to Pyjion in faq.md

---

content/en/about.md

Update Fosstodon link for SciPy. The correct link is:
<https://fosstodon.org/@scipy>
This is related to PR #602.

DOC: Update Fosstodon link for SciPy

---

content/en/community.md

This is a small documentation improvement proposal for the community document.
The original document mentions joining the #scipy channel on Discord, but it does not provide a link to join the Scientific Python Discord server.
While checking the Markdown file, we might notice that the title itself is a link to the Discord invitation. 
However, it would be better to include a clear explanation, similar to how to join the slack channel, to make it more user-friendly.

Add Discord invite link sentence

---

content/en/community.md

In the current document, the link https://conference.scipy.org/ is used as the homepage for SciPy Japan. 
However, this link does not actually lead to the homepage of SciPy Japan.
Additionally, SciPy Japan has not been held since [2020](https://www.scipyjapan.scipy.org/). 
After confirming with Koyama san (@tkoyama010), one of the organizers, I confirmed that SciPy Japan has been integrated into the following conference:
SciPyData - connpass: https://scipydata.connpass.com/
Therefore, I believe this link should be used as the reference for the SciPy conference in Japan.

Update Japan SciPy conference name and link to current one.

---

content/en/about.md

In the `about.md` page: Add accent to the name `İ`lhan Polat with a dot on top of the "I".
In the BibTeX entry of `citing-scipy.md`, the name is written as `{\.I}`lhan Polat.

DOC: Add accent to the name İlhan Polat

---

content/en/news.md

Announce SciPy `1.15.2`.
The assets have been published on GitHub and PyPI; I'll deal with the final steps of the process tomorrow.

Announce SciPy 1.15.2

---

content/en/news.md

Announce SciPy `1.15.3`.
The assets have been published on GitHub and PyPI.

Announce SciPy 1.15.3

---

content/en/news.md

Announce SciPy `1.16.1` after the release this morning, highlighting that this is the first stable release to support Python `3.14`.

Announce SciPy 1.16.1

---

content/en/news.md

Announce SciPy `1.16.2`, including a mention that this is the first stable release to provide "Windows on ARM" wheels on PyPI.

Announce SciPy 1.16.2
