www/scipylib/faq.rst

Add brief description of where to get help

---

www/index.rst

Add Scipy 0.15.0 to news

---

www/scipylib/faq.rst

From Python 3.5, we will have one.
Fixes gh-80

Update FAQ entry on matmul operator

---

www/topical-software.rst

I found mpmath useful for me. I think it may be useful for others with same requirements.

Add mpmath to the list

---

www/index.rst

NEWS: announce numpy 1.10.0rc1 release.

---

www/topical-software.rst

Also fixes a formatting issue on that page.

Add Autograd to topical software list.

---

www/scipylib/faq.rst

Title is self-explanatory.  Closes #105.

DOC: Updated pyfits URL

---

www/scipylib/building/windows.rst

MAINT: Grammar fixes for building on Windows

---

www/install.rst

Title is self-explanatory.  Closes #154.

Update installation options

---

www/citing.rst

Fix my name in the scikit-image paper authors list

---

www/install.rst

Add pip to the install options.  Update homebrew instructions.
See: https://github.com/scipy/scipy/issues/6558

DOC: update install instructions with pip

---

www/index.rst
www/past-news.rst

Also move Numpy 1.12.1rc1 to past-news.

Announce NumPy 1.12.1.

---

www/scipylib/mailing-lists.rst

**Merge only after the move has actually taken place!**

DOC: update mailing lists page for move to python.org infrastructure

---

www/Makefile

served from ``/var/www/html`` now

MAINT: update location to push built site to:

---

www/index.rst
www/past-news.rst

These now come a bit late, but probably better than never.
(The euroscipy call will probably be extended.)

Advertise scipy/euroscipy conferences

---

www/topical-software.rst

Just a good specialized optimization software in python.

Add CMA as python optimiser in topical-software.rst

---

www/topical-software.rst

List QmeQ package in Quantum mechanics section.

Add QmeQ package to topical-software.rst

---

www/index.rst
www/past-news.rst

Also move older NumPy annoucements to past-news.

Announce NumPy 1.13.3

---

www/_templates/sitenav.html
www/index.rst

Closes gh-225
ping @pv @ksurya - I'll mention this on the mailing list as well.

MAINT: remove SciPy Central links. 

---

www/index.rst

Will merge this once the binaries are up on PyPI and the release announcement is ready to be sent.

Announce release of SciPy 1.0.0

---

www/scipylib/mailing-lists.rst

Add some links to the "mailing list" page.

Add links to CoC and freenode webchat

---

www/citing.rst

See "NumPy default citation" thread at
https://mail.python.org/pipermail/numpy-discussion/2017-September/077176.html

DOC: update NumPy citation.

---

www/citing.rst

Same as https://github.com/scipy/scipy/pull/8832 ;-)

Hyperlink DOIs against preferred resolver

---

www/_templates/sitenav.html
www/codes-of-conduct.rst
www/index.rst
www/scipylib/index.rst

I asked a friend for feedback on our CoC, and she noted that it was not very easy to find.  I added it to the sidebar, and will make another PR to add it to the README as well.

Add Code of Conduct to navigation sidebar

---

www/codes-of-conduct.rst

Addresses comment of @tacaswell on gh-257

Update CoC link for Matplotlib. 

---

www/index.rst

Announce SciPy 1.2.0

---

www/index.rst

Announce SciPy 1.2.1

---

www/scipylib/faq.rst

Closes gh-https://github.com/scipy/scipy/issues/9825

MAINT: a number of edits to FAQ questions.

---

www/topical-software.rst

Adding [Colour](https://www.colour-science.org/) to the *Miscellaneous* list.

Add "Colour" to "Miscellaneous" list.

---

www/index.rst

Announce SciPy 1.3.0

---

www/index.rst

Announce SciPy 1.2.2

---

www/index.rst

Announce SciPy `1.3.1`, if we're still doing that stuff here -- can't keep track of all the website changes!

Announce SciPy 1.3.1

---

www/docs.rst
www/getting-started.rst

Part of numpy/numpy.org#25 and friends

reference numpy.org for all things numpy

---

www/install.rst

I've just reworked the content on the install page, hopefully making it a bit clearer and smoother.

Revised Install Page

---

www/getting-started.rst

I rewrote the "Getting Started" page.  Hopefully better.

Getting Started Page

---

www/index.rst

Announce SciPy 1.3.2

---

www/docs.rst
www/index.rst

I removed the outdated ad about taking part in our survey and added news about the results.

DOC: survey update

---

www/index.rst

Announce SciPy 1.3.3

---

www/_templates/sitenav.html
www/about.rst
www/bug-report.rst
www/citing.rst
www/codes-of-conduct.rst
www/docs.rst
www/getting-started.rst
www/index.rst
www/install.rst
www/scikits.rst
www/scipylib/bug-report.rst
www/scipylib/dev-zone.rst
www/scipylib/donations.rst
www/scipylib/download.rst
www/scipylib/faq.rst
www/scipylib/index.rst
www/scipylib/license.rst
www/scipylib/mailing-lists.rst
www/sphinxext/ipython_console_highlighting.py
www/stackspec.rst
www/topical-software.rst

Stylistic revision, punctuation, typos, etc. Also, closes gh-306.

DOC: stylistic consistency, typos, formatting

---

www/docs.rst

Just a very minor revision that escaped my attention last time:
Changed Numpy -> NumPy and Scipy -> SciPy, also Pandas -> pandas

DOC: update docs.rst

---

README.md

Removed the README.txt and added the README.md for a better documentation experience.
The README.md file can later prove useful once proper unit tests and dev cycles are setup for the website; and for many other purposes.

Added README.md file for better documentation.

---

www/index.rst

Announce SciPy 1.4.0

---

www/index.rst

Announce SciPy 1.4.1

---

www/index.rst

Announce SciPy 1.2.3

---

www/citing.rst

* adjust the citation for SciPy 1.0 to point to
the NMETH journal article/DOI; volume/page numbers
should come out next month

MAINT: update SciPy 1.0 citation

---

www/citing.rst

* volume & page numbers are [now available](https://www.nature.com/articles/s41592-019-0686-2#citeas)
* a little whitespace cleanup, hopefully

MAINT: update SciPy citation

---

www/index.rst

Announce SciPy 1.5.0

---

www/index.rst

Announce SciPy 1.5.1

---

www/index.rst

Announce SciPy 1.5.2

---

www/scipylib/mailing-lists.rst

Addresses the website part of gh-308. New look:
Old look:

Improve info for and rendering on mailing lists

---

www/citing.rst

Update Citing page

---

www/index.rst

Announce SciPy 1.5.3

---

www/index.rst

Announce SciPy 1.5.4

---

www/index.rst

Announce SciPy 1.6.0

---

www/index.rst

Announce SciPy 1.6.1
I won't quite have time for the doc artifacts tonight though; will try tomorrow.

Announce SciPy 1.6.1

---

www/index.rst

Announce SciPy `1.6.2`
I'll likely do the docs build/upload another day though.

Announce SciPy 1.6.2

---

www/index.rst

Announce SciPy 1.6.3

---

www/index.rst

Announce SciPy 1.7.0

---

www/index.rst

Announce SciPy 1.7.1

---

www/scipylib/mailing-lists.rst

xref https://github.com/scipy/scipy/issues/14239#issuecomment-904653674
This removes the IRC section from the mailing list page.

DOC: remove IRC section

---

netlify.toml

Add redirects

---

config.yaml
content/en/news.md

Announce SciPy `1.7.2` release.
Let me know if I've done something wrong so I can learn the new process.

Announce SciPy 1.7.2

---

config.yaml
content/en/dev-zone.md
content/en/donations.md
content/en/faq.md
netlify.toml

This is for after @rgommers renames the master branch main.

Rename master to main

---

README.md
config.yaml

MAINT: Analytics using plausible.io with scientific-python

---

config.yaml
content/en/press-kit.md
netlify.toml

@tupui Would you double-check this?  In particular, take a look at f8ff69c2b037b.

Run linkcheck in CI

---

content/en/contribute.md

See https://github.com/numpy/numpy.org/pull/545.  Closes #446.

Remove redundant table of contents

---

content/en/news.md

* Announce SciPy 1.8.0
* Please do look over the changes since the new website stuff has been in flux a bit; I tried to mimic my most recent release announcement

Announce SciPy 1.8.0

---

static/teams/maintainers.html
static/teams/triage-team.html
static/teams/web-team.html

@stefanv you are not yet in the web team of SciPy, I had to add you manually. ~Can you click to request to join the team?~ Actually I think you're an owner and should be able to add yourself.
https://github.com/orgs/scipy/teams/web-team/members

Add Melissa to triage and Ralf to web

---

content/en/about.md

Hey @noatamir and @tupui I have fixed this. And I loved to do this. Please review my PR.
Thanks!
#464

Broken Link to Governance

---

content/en/news.md

Announce SciPy 1.8.1

---

content/en/download.md

Fix broken link to build instructions

---

content/en/news.md

This should hopefully help get more eyes from the SciPy website to the SciPy Conference!

Create news entry for SciPy 2022

---

config.yaml

Maybe we can also add Slack, Discord (but discord would be the Scientific Python one) and discuss? WDYT?

Add twitter to socials in footer

---

content/en/news.md

Announce SciPy 1.9.0

---

content/en/news.md

Announce SciPy 1.9.1

---

content/en/news.md

Announce SciPy 1.9.2

---

content/en/news.md

Announce SciPy 1.9.3

---

static/teams/emeritus-maintainers.html
static/teams/maintainers.html
static/teams/triage-team.html
static/teams/web-team.html

FYI, @stefanv you are still not in the GH list for the web team and I think you should be. I manually update the list to have you there.

Update team members

---

content/en/news.md

Announce SciPy 1.10.0

---

content/en/news.md

Announce SciPy 1.10.1

---

static/teams/emeritus-maintainers.html
static/teams/maintainers.html
static/teams/triage-team.html
static/teams/web-team.html

- add @j-bowhay to the maintainer team 🎉 
- add Daniel Schmitz to the triage team 🎉 
- move Peter Larsen to the emeritus one 🙇

Update maintainer and emeritus lists

---

content/en/news.md

Announce SciPy 1.11.0

---

content/en/news.md

Announce SciPy 1.11.2

---

content/en/news.md

Announce SciPy 1.11.3

---

netlify.toml
static/teams/emeritus-maintainers.html
static/teams/maintainers.html
static/teams/triage-team.html
static/teams/web-team.html

This is a major update. It notably adds a dark/light theme and integrates a lot of styling from pydata-sphinx-theme. This will improve accessibility and should make the experience cleaner for users moving between the homepage and the documentation.
See https://github.com/scientific-python/scientific-python-hugo-theme/blob/main/CHANGELOG.md
Currently, you are (essentially) using v0.1 of the theme.

Update theme (0.4)

---

content/en/news.md

Announce SciPy 1.11.4

---

content/en/news.md

Announce SciPy 1.12.0

---

content/en/teams/maintainers.toml

Add Dan to the team

---

content/en/news.md

Announce SciPy 1.14.0

---

content/en/teams/maintainers.toml
content/en/teams/triage-team.toml
content/en/teams/web-team.toml

Updates the teams page. Congrats @fancidev @nickodell @scottshambaugh 🎉

MAINT: update teams

---

content/en/news.md

Announce SciPy 1.15.0

---

content/en/news.md

Announce SciPy `1.15.1` -- same-day delivery :)

Announce SciPy 1.15.1

---

config.yaml
content/en/about.md

Add icon for discourse and social media section

---

content/en/install.md

Maybe, Integrated Development Environments is right?

Fix a typo of IDE

---

content/en/teams/maintainers.toml
content/en/teams/triage-team.toml

@nickodell, do you need an apostrophe in your surname?

MAINT: move Nick ODell to maintainer team

---

content/en/news.md

Announce SciPy `1.16.0` after releasing this morning.

Announce SciPy 1.16.0

---

Makefile
content/en/teams/index.md
content/en/teams/triage-team.toml
content/en/teams/typing-team.toml

add typing team
